export enum AuditUserAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  USER_EMAIL_CHANGE_REQUESTED = 'USER_EMAIL_CHANGE_REQUESTED',
  USER_EMAIL_CHANGE_CONFIRMED = 'USER_EMAIL_CHANGE_CONFIRMED',
}